### ISSUE TITLE
MHGen DLCXCipher?

### ISSUE THREAD

**Issue by hmaniac** [svanheulen/mhef#11]
Hello, so far I've been able to get the keys, thanks to you making it simple, but now I'm not sure what to do here, or am I missing a step? This came up. Thanks again.

c:\Users\Zangief\Downloads\mhef-master\examples\n3ds>dlcx.py d USA N3uExdqeA6r8jusbnN7mBRVWS8qe9sDaLe6viEVGRSA q112005.arc q112005--00.arc
Traceback (most recent call last):
  File "C:\Users\Zangief\Downloads\mhef-master\examples\n3ds\dlcx.py", line 31, in <module>
    dc = mhef.n3ds.DLCXCipher(mhef.n3ds.MHX_JP, args.key)
AttributeError: 'module' object has no attribute 'DLCXCipher'

**Comment by svanheulen** [comment]
It looks like you have an older version of the `mhef` module installed. You can see your installed version with this command: `pip show mhef`
You need to have version 1.2.0 installed.

**Comment by hmaniac** [comment]
Alright, that seemed like it was the issue. I did this for MH4U, assuming I knew how to do it, and overlooked the mhef setup. A noob error on my end, and sorry to pester you again but new issue arose about keys. Should I write a new issue or continue here?

**Comment by svanheulen** [comment]
Start a new issue, please.
