### ISSUE TITLE
tool download_n3ds

### ISSUE THREAD

**Issue by yp05327** [svanheulen/mhef#12]
mhx jpn download url has changed
it's http://spector.capcom.co.jp/3ds/mhx_new_jp/ now.
I just have mhx jpn so others I don't know whether changed or not.

**Comment by svanheulen** [comment]
Yeah, they released v1.3.0 update for MHX JPN. It looks like they added the RSA signature code from Generations. I'll fix this and a few other things once I can get the update.

**Comment by svanheulen** [comment]
All fixed :)
