### ISSUE TITLE
UNrecognized argument

### ISSUE THREAD

**Issue by 000191750** [svanheulen/mhef#14]
![qq 20170318233304](https://cloud.githubusercontent.com/assets/14256927/24073549/f9b51022-0c33-11e7-903b-427d4508399e.png)
Dear maset,
 I've used the old key to dencrypt my old dlc,but it didn't work,and how can I updata my old dlc?
please teach me,thank you .

**Comment by svanheulen** [comment]
You have an extra argument. Remove the `None`.

**Comment by 000191750** [comment]
![error](https://cloud.githubusercontent.com/assets/14256927/24073644/a560d50e-0c35-11e7-9417-dce2405c1053.png)
I've tried but I error again

**Comment by svanheulen** [comment]
You probably have an incorrect encryption key. Did you get the quest file using the download script or did you extract it from your save file?

**Comment by 000191750** [comment]
I got the key from the mhx_data_manager,and my mhx is the latest version.

**Comment by 000191750** [comment]
oh,I extract it from my save file

**Comment by svanheulen** [comment]
Did you also export the quest file with MHX Data Manager? If you did, it's already decrypted and there's no need to use this on it.

**Comment by 000191750** [comment]
umm... actually only when I dencrypt it has this problem,when I encrypt it the error didn't exsist

**Comment by svanheulen** [comment]
Yes, that's because the quests in your save file are not encrypted. They're only encrypted if you download them directly from the Capcom's server using the `tools/download_n3ds.py` script.

**Comment by 000191750** [comment]
but I can't use mhxqe to open the quest,I think it has been encrypted

**Comment by svanheulen** [comment]
You can confirm that it's not encrypted by opening it in a hex editor. If the first 3 bytes are `ARC` then it's not encrypted.

**Comment by 000191750** [comment]
I use UE to open it ，the first 3 bytes are not ARC，so it is not encrypted，right？

**Comment by svanheulen** [comment]
Correct. So the issue must be with mhxqe. Could you open an issue on that repo please and describe what happens when you try opening this quest?

**Comment by svanheulen** [comment]
Oh you said they're NOT `ARC`... then your quest file is just corrupt. Redownload it in the game and export it again with MHX Data manager

**Comment by 000191750** [comment]
yes,maybe the issue is that I should use the old version mhef to dencrypt it,and encrypt it in this latest version.I' ll try it tomorrow .Thank you very much.It's deep night here,good night.

**Comment by svanheulen** [comment]
No, you don't need to use mhef at all. The quests in your save file are already decrypted and mhxqe needs them to be decrypted. So just export the quest with MHX Data Manager and then load the exported files with mhxqe.

**Comment by 000191750** [comment]
umm... I tried ，I can encrypt now,but I can't download it with SKFU(a proxy server),I want to know how to use the blowfish key and the public key?

**Comment by svanheulen** [comment]
It's not possible to proxy quests any more. The newest MHX update has RSA signatures on DLC that are impossible to forge. You can just use MHX Data Manager to import the quests after you modify them (be sure to leave them decrypted).

**Comment by 000191750** [comment]
OH, what a pity!Thank you very much my master.

**Comment by 000191750** [comment]
umm... Another problem，How to setup the mhx data manager on my 3ds, which isn't cracked

**Comment by svanheulen** [comment]
https://github.com/svanheulen/mhx_data_manager/releases
The zip file has the HBL version, just unzip it to the root of your SD card and run it from the Homebrew Launcher. If it locks up when you try starting it delete the `/3ds/mhx_data_manager/mhx_data_manager.xml` file.

**Comment by 000191750** [comment]
oh,thank you ,I 'll try it now
