### ISSUE TITLE
how can i get the blowfish encryption key

### ISSUE THREAD

**Issue by Ch0p** [svanheulen/mhef#6]
i using mh4g Korean ver.

but when i using this tool, cannot decrypted any data.

so i want to how get encryption key in my version.

could you give me this information...?

**Comment by svanheulen** [comment]
If you can run NTR CFW on your 3DS I can walk you through the process of obtaining the key.

**Comment by Ch0p** [comment]
thx for reply :D

but NTR CFW cannot run in korea. because we cannot download cubic ninja :(

i have to find another way :)

**Comment by svanheulen** [comment]
NTR is just the way I did it, but really all you need to be able to do is read the game's memory while it's running. I have someone in my other repo asking the same thing: https://github.com/svanheulen/mhqs/issues/2

**Comment by svanheulen** [comment]
The Japanese key was added thanks to @Humankimchi
Can you try using that? I'm not sure if the Korean game uses the same key or it's own

**Comment by svanheulen** [comment]
The Korean key is in there now, be sure to get the newest version and reinstall it
