### ISSUE TITLE
Having decrypt problem?

### ISSUE THREAD

**Issue by chinanoahli** [svanheulen/mhef#8]
```
C:\Users\UDload\Desktop\MHX\mhef-master\examples\n3ds>python dlc.py d X JPN q1010002.arc q1010002-1.arc
Traceback (most recent call last):
  File "dlc.py", line 47, in <module>
    dc.decrypt_file(args.inputfile, args.outputfile)
  File "C:\Python33\lib\site-packages\mhef\n3ds.py", line 207, in decrypt_file
    dlc = self.decrypt(dlc)
  File "C:\Python33\lib\site-packages\mhef\n3ds.py", line 197, in decrypt
    raise ValueError('Invalid SHA1 hash in footer.')
ValueError: Invalid SHA1 hash in footer.
```

**Comment by chinanoahli** [comment]
Is it the DL key issue? How can I get the key without customize firmware?

**Comment by svanheulen** [comment]
Yes, they change the key every 48 hours and I haven't been keeping up on it. I might just remove it from the code all together since it's always out of date... but I'll update it now, just use it soon because it wont last long.

**Comment by chinanoahli** [comment]
Thank you, and I will try to get the key by my self, now I am going to try to install A9 on my n3ds.
