### ISSUE TITLE
I'm trying to proxy the MH generation DLC to my 3ds

### ISSUE THREAD

**Issue by PhantomGS** [svanheulen/mhef#9]
Hey master,
I've met a problem when decrypt the arc file. Can you tell me what's wrong with it?(q1010002.arc)
(it says:"Invalid SHA1 hash in footer")Ok i've seen the previous comment on this problem,i just wonder where to get the keys...
And where can i find the list of dlc like mh4u?

**Comment by svanheulen** [comment]
You can get the list of available quests by downloading and decrypting the `eventQuestList.bin` and `challangeQuestList.bin` files. As for the getting the key, the script `tools/get_mhx_key.py` will allow you to get the newest encryption key from MHX using NTR CFW.

**Comment by PhantomGS** [comment]
thx~

**Comment by PhantomGS** [comment]
Can you change the key in the file now? Sorry I didin't installed the NTR CFW system : ( 
Much appreciation！

**Comment by svanheulen** [comment]
The current key is `3s8DywfYpz3gB9oeb0viLNanUCtRM92hOXwWFqXUf5yxPOiaJigjy3Tm`
Use it soon, it will only work for 48 hours or less.

**Comment by PhantomGS** [comment]
Thank you for your help, i do worked!
But when i use the proxy to cover the dlc (q1010117.arc cover q1110103.arc )it shows error 0903311
I wonder what is the problem, does it matter that q1010117 is a JPN DLC? I used your quest editor which is a web page and then i packed it encrypt it and proxy to the 3ds. 
 If it's convinient can you just give me some sample quests(fun quest or reword quest) to try download and cover DLC?
Much appreciation!!!

**Comment by svanheulen** [comment]
Unfortunately you can not proxy quests into MHGen. They added a signature to the DLC which is impossible to forge. The only way to get custom quests into MHGen is to use homebrew. I have an app that can do it here: https://github.com/svanheulen/mhx_data_manager

Also, in the future, please create a new issue rather then modifying an unrelated one.

**Comment by PhantomGS** [comment]
Thank you very much! I will keep it in mind and try you apps
